export const tiles: Array<object> = [
	{
		"Tile Number": 1,
		"Can Pair With": "T2",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		topMatches: [2],
		bottomMatches: [],
		count: 9,
	},
	{
		"Tile Number": 2,
		"Can Pair With": "B1, T28",
		Points: "B=1, T=2",
		isTop: true,
		isBottom: true,
		topPoints: 2,
		bottomPoints: 1,
		topMatches: [28],
		bottomMatches: [1],
		count: 2,
	},
	{
		"Tile Number": 3,
		"Can Pair With": "T4, T11, T18",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		topMatches: [4, 11, 18],
		bottomMatches: [],
		count: 2,
	},
	{
		"Tile Number": 4,
		"Can Pair With": "B3",
		Points: 5,
		isTop: true,
		isBottom: false,
		topPoints: 5,
		bottomPoints: 0,
		topMatches: [],
		bottomMatches: [3],
		count: 4,
	},
	{
		"Tile Number": 5,
		"Can Pair With": "T6, T12",
		Points: 2,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 2,
		topMatches: [6, 12],
		bottomMatches: [],
		count: 12,
	},
];
