export const tilesObject: Array<object> = [
	{
		tileNumber: 1,
		pairsWith: "T2",
		Points: 1,
		isTop: true,
		isBottom: false,
		topPoints: 1,
		bottomPoints: 0,
		ifTopMatchesWith: [2],
		ifBottomMatchesWith: [],
		count: 9,
	},
	{
		tileNumber: 2,
		pairsWith: "B1, T28",
		Points: "B=1, T=2",
		isTop: true,
		isBottom: true,
		topPoints: 2,
		bottomPoints: 1,
		ifTopMatchesWith: [28],
		ifBottomMatchesWith: [1],
		count: 11,
	},
	{
		tileNumber: 3,
		pairsWith: "T4, T11, T18",
		Points: 1,
		isTop: true,
		isBottom: false,
		topPoints: 1,
		bottomPoints: 0,
		ifTopMatchesWith: [4, 11, 18],
		ifBottomMatchesWith: [],
		count: 10,
	},
	{
		tileNumber: 4,
		pairsWith: "B3",
		Points: 5,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 5,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [3],
		count: 2,
	},
	{
		tileNumber: 5,
		pairsWith: "T6, T12",
		Points: 2,
		isTop: true,
		isBottom: false,
		topPoints: 2,
		bottomPoints: 0,
		ifTopMatchesWith: [6, 12],
		ifBottomMatchesWith: [],
		count: 5,
	},
	{
		tileNumber: 6,
		pairsWith: "B5",
		Points: 4,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 4,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [5],
		count: 2,
	},
	{
		tileNumber: 7,
		pairsWith: "T8",
		Points: 2,
		isTop: true,
		isBottom: false,
		topPoints: 2,
		bottomPoints: 0,
		ifTopMatchesWith: [8],
		ifBottomMatchesWith: [],
		count: 4,
	},
	{
		tileNumber: 8,
		pairsWith: "B8",
		Points: 2,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 2,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [8],
		count: 4,
	},
	{
		tileNumber: 9,
		pairsWith: "T10, T11",
		Points: 1,
		isTop: true,
		isBottom: false,
		topPoints: 1,
		bottomPoints: 0,
		ifTopMatchesWith: [10, 11],
		ifBottomMatchesWith: [],
		count: 14,
	},
	{
		tileNumber: 10,
		pairsWith: "B9,B19",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [9, 19],
		count: 16,
	},
	{
		tileNumber: 11,
		pairsWith: "B9, B3, T16",
		Points: "B=5, T=8",
		isTop: true,
		isBottom: true,
		topPoints: 8,
		bottomPoints: 5,
		ifTopMatchesWith: [16],
		ifBottomMatchesWith: [3, 9],
		count: 5,
	},
	{
		tileNumber: 12,
		pairsWith: "B5",
		Points: 2,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 2,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [5],
		count: 3,
	},
	{
		tileNumber: 13,
		pairsWith: "T14",
		Points: 4,
		isTop: true,
		isBottom: false,
		topPoints: 4,
		bottomPoints: 0,
		ifTopMatchesWith: [14],
		ifBottomMatchesWith: [],
		count: 2,
	},
	{
		tileNumber: 14,
		pairsWith: "B13, T27",
		Points: "B=4, T=1",
		isTop: true,
		isBottom: true,
		topPoints: 1,
		bottomPoints: 4,
		ifTopMatchesWith: [27],
		ifBottomMatchesWith: [13],
		count: 6,
	},
	{
		tileNumber: 15,
		pairsWith: "B15, T16",
		Points: 1,
		isTop: true,
		isBottom: true,
		topPoints: 1,
		bottomPoints: 1,
		ifTopMatchesWith: [16],
		ifBottomMatchesWith: [15],
		count: 24,
	},
	{
		tileNumber: 16,
		pairsWith: "B11",
		Points: 8,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 8,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [11],
		count: 1,
	},
	{
		tileNumber: 17,
		pairsWith: "T18",
		Points: 9,
		isTop: true,
		isBottom: false,
		topPoints: 9,
		bottomPoints: 0,
		ifTopMatchesWith: [18],
		ifBottomMatchesWith: [],
		count: 1,
	},
	{
		tileNumber: 18,
		pairsWith: "B17, B3",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [3, 17],
		count: 7,
	},
	{
		tileNumber: 19,
		pairsWith: "T10",
		Points: 2,
		isTop: true,
		isBottom: false,
		topPoints: 2,
		bottomPoints: 0,
		ifTopMatchesWith: [10],
		ifBottomMatchesWith: [],
		count: 4,
	},
	{
		tileNumber: 20,
		pairsWith: "B21, T21",
		Points: "B=4, T=3",
		isTop: true,
		isBottom: true,
		topPoints: 3,
		bottomPoints: 4,
		ifTopMatchesWith: [21],
		ifBottomMatchesWith: [21],
		count: 4,
	},
	{
		tileNumber: 21,
		pairsWith: "B20, T20",
		Points: "B=3, T=4",
		isTop: true,
		isBottom: true,
		topPoints: 4,
		bottomPoints: 3,
		ifTopMatchesWith: [20],
		ifBottomMatchesWith: [20],
		count: 4,
	},
	{
		tileNumber: 22,
		pairsWith: "B22, T22",
		Points: 1,
		isTop: true,
		isBottom: true,
		topPoints: 1,
		bottomPoints: 1,
		ifTopMatchesWith: [22],
		ifBottomMatchesWith: [22],
		count: 12,
	},
	{
		tileNumber: 23,
		pairsWith: "B23, T23, T24",
		Points: 1,
		isTop: true,
		isBottom: true,
		topPoints: 1,
		bottomPoints: 1,
		ifTopMatchesWith: [23, 24],
		ifBottomMatchesWith: [23],
		count: 17,
	},
	{
		tileNumber: 24,
		pairsWith: "B23",
		Points: 19,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 19,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [23],
		count: 1,
	},
	{
		tileNumber: 25,
		pairsWith: "B25, T25",
		Points: 1,
		isTop: true,
		isBottom: true,
		topPoints: 1,
		bottomPoints: 1,
		ifTopMatchesWith: [25],
		ifBottomMatchesWith: [25],
		count: 8,
	},
	{
		tileNumber: 26,
		pairsWith: "B15, B29",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [15, 29],
		count: 8,
	},
	{
		tileNumber: 27,
		pairsWith: "B14",
		Points: 1,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 1,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [14],
		count: 4,
	},
	{
		tileNumber: 28,
		pairsWith: "B2",
		Points: 6,
		isTop: false,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 6,
		ifTopMatchesWith: [],
		ifBottomMatchesWith: [2],
		count: 2,
	},
	{
		tileNumber: 29,
		pairsWith: "T26, B29, T29",
		Points: 8,
		isTop: true,
		isBottom: true,
		topPoints: 8,
		bottomPoints: 8,
		ifTopMatchesWith: [26, 29],
		ifBottomMatchesWith: [29],
		count: 4,
	},
	{
		tileNumber: 30,
		pairsWith: "B30, T30",
		Points: 10,
		isTop: true,
		isBottom: true,
		topPoints: 10,
		bottomPoints: 10,
		ifTopMatchesWith: [30],
		ifBottomMatchesWith: [30],
		count: 2,
	},
	{
		tileNumber: 31,
		pairsWith: "any",
		Points: 0,
		isTop: true,
		isBottom: true,
		topPoints: 0,
		bottomPoints: 0,
		ifTopMatchesWith: [100],
		ifBottomMatchesWith: [100],
		count: 4,
	},
];
